# Generated by Django 3.1.10 on 2021-05-09 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='USD', max_length=3, verbose_name='ISO 4217 currency codes')),
                ('currency_name', models.CharField(max_length=128, verbose_name='Supported Currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('transaction_id', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('transfer_to', models.CharField(editable=False, max_length=255)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('debit', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('sent_amount', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.currency')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('transfer_from', models.CharField(editable=False, max_length=255)),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('recipient', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=128)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('debit', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('sent_amount', models.IntegerField()),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.currency')),
            ],
        ),
    ]
