# Generated by Django 3.1.10 on 2021-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3, primary_key=True, serialize=False, verbose_name='ISO 4217 currency codes'),
        ),
    ]
