# Generated by Django 3.1.10 on 2021-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20210510_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO 4217 currency codes'),
        ),
    ]
