# Generated by Django 3.1.10 on 2021-05-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20210510_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
