# Generated by Django 3.1.10 on 2021-05-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '__first__'),
        ('users', '0004_auto_20210509_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='converter.currency'),
            preserve_default=False,
        ),
    ]
