# Generated by Django 3.1.10 on 2021-05-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
        ('users', '0007_remove_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.SET_DEFAULT, to='converter.currency'),
        ),
    ]
