# Generated by Django 3.1.10 on 2021-05-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
        ('users', '0008_userprofile_preferred_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.currency'),
        ),
    ]
