# Generated by Django 3.1.10 on 2021-05-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20210510_1358'),
        ('users', '0009_auto_20210510_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='converter.currency'),
        ),
    ]
