# Generated by Django 3.1.10 on 2021-05-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20210510_1521'),
        ('users', '0010_auto_20210510_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.currency'),
        ),
    ]
